source 'https://cdn.cocoapods.org'

use_frameworks!

target 'iosApp' do
    platform :ios, '26.4.1'
    pod 'ylcs-app', :path => '../app/portal'
    pod 'MMKV', '2.3.0'
    pod 'SGQRCode', '4.1.0'
end
