name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths-ignore:
      - '**.md'
      - 'ylcs-docs/**'
      - 'design/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'ylcs-docs/**'
      - 'design/**'

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.filter.outputs.android }}
      ios: ${{ steps.filter.outputs.ios }}
      desktop: ${{ steps.filter.outputs.desktop }}
      web: ${{ steps.filter.outputs.web }}
      server: ${{ steps.filter.outputs.server }}
      modManager: ${{ steps.filter.outputs.modManager }}
      landpage: ${{ steps.filter.outputs.landpage }}
      gallery: ${{ steps.filter.outputs.gallery }}
      modernScreen: ${{ steps.filter.outputs.modernScreen }}
    steps:
      - name: Checkout Code
        uses: $/.github/actions/checkout
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Detect File Changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            common: &common
              - '.github/actions/**'
              - '.github/workflows/**'
              - 'gradle/**'
              - 'buildSrc/**'
              - 'ylcs-module/**/commonMain/**'
              - 'ylcs-app/cs/**'
              - 'ylcs-app/mod/**'
              - 'gradle.properties'
              - 'settings.gradle.kts'
              - 'build.gradle.kts'
              - 'libs.versions.toml'
            client: &client
              - *common
              - 'ylcs-app/app/**/commonMain/**'
              - 'ylcs-app/app/**/build.gradle.kts'
            android:
              - *client
              - 'ylcs-module/**/jvmMain/**'
              - 'ylcs-module/**/androidMain/**'
              - 'ylcs-app/app/**/jvmMain/**'
              - 'ylcs-app/app/**/androidMain/**'
              - 'ylcs-app/android-app/**'
            ios:
              - *client
              - 'ylcs-module/**/appleMain/**'
              - 'ylcs-module/**/iosMain/**'
              - 'ylcs-app/app/**/nativeInterop/**'
              - 'ylcs-app/app/**/appleMain/**'
              - 'ylcs-app/app/**/iosMain/**'
              - 'ylcs-app/iosApp/**'
            desktop:
              - *client
              - 'ylcs-module/**/jvmMain/**'
              - 'ylcs-module/**/desktopMain/**'
              - 'ylcs-app/app/**/jvmMain/**'
              - 'ylcs-app/app/**/desktopMain/**'
              - 'ylcs-app/desktop-app/**'
            web:
              - *client
              - 'ylcs-module/**/webMain/**'
              - 'ylcs-module/**/jsMain/**'
              - 'ylcs-module/**/wasmJsMain/**'
              - 'ylcs-app/app/**/webMain/**'
              - 'ylcs-app/app/**/jsMain/**'
              - 'ylcs-app/app/**/wasmJsMain/**'
              - 'ylcs-app/web-app/**'
            server:
              - *common
              - 'ylcs-app/server/**'
            modManager:
              - *common
              - 'ylcs-app/mod-manager/**'
            landpage:
              - *common
              - 'ylcs-app/landpage/**'
            gallery:
              - *common
              - 'ylcs-app/gallery/**'
            modernScreen:
              - *common
              - 'ylcs-app/modern-screen/**'

  build-android:
    name: Build Android
    needs: changes
    if: ${{ needs.changes.outputs.android == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: ubuntu-latest
      task: ylcs-app:android-app:androidPackage
      submodules: recursive
      android: true

  build-ios:
    name: Build iOS
    needs: changes
    if: ${{ needs.changes.outputs.ios == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: macos-26
      task: ylcs-app:app:portal:linkDebugFrameworkIosArm64
      submodules: recursive

  build-desktop:
    name: Build Desktop
    needs: changes
    if: ${{ needs.changes.outputs.desktop == 'true' }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: ${{ matrix.os }}
      task: ylcs-app:desktop-app:desktopJar
      submodules: recursive
      msvc: true
      gtk: true

  build-web:
    name: Build Web
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: ubuntu-latest
      task: ylcs-app:web-app:wasmJsJar
      submodules: recursive

  build-server:
    name: Build Server
    needs: changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: ubuntu-latest
      task: ylcs-app:server:linkDebugExecutableLinux

  build-modManager:
    name: Build Mod Manager
    needs: changes
    if: ${{ needs.changes.outputs.modManager == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: windows-latest
      task: ylcs-app:mod-manager:desktopJar
      msvc: true

  build-landpage:
    name: Build Landpage
    needs: changes
    if: ${{ needs.changes.outputs.landpage == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: ubuntu-latest
      task: ylcs-app:landpage:jsJar

  build-gallery:
    name: Build Rachel UI Gallery
    needs: changes
    if: ${{ needs.changes.outputs.gallery == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: windows-latest
      task: ylcs-app:gallery:desktopJar

  build-modernScreen:
    name: Build Rachel Modern Screen
    needs: changes
    if: ${{ needs.changes.outputs.modernScreen == 'true' }}
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: windows-latest
      task: ylcs-app:modern-screen:desktopJar