name: ReleaseMacOS
on:
  push:
    tags:
      - 'macos*'
jobs:
  package-macos:
    name: Package macOS
    runs-on: macos-26
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build

      - name: Build
        run: ./gradlew ylcs-app:desktop-app:desktopPublish