name: ReleaseWindows
on:
  push:
    tags:
      - 'windows*'
jobs:
  package-windows:
    name: Package Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build
        with:
          msvc: 'true'

      - name: Build
        run: ./gradlew ylcs-app:desktop-app:desktopPublish