name: ReleaseAndroid
on:
  push:
    tags:
      - 'android*'
jobs:
  package-android:
    name: Package Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: gradle
          cache-dependency-path: |
            ./*.gradle*
            ./**/gradle-wrapper.properties

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: ./gradlew ylcs-app:androidApp:androidPublish
