name: ReleaseWeb
on:
  push:
    tags:
      - 'web*'
jobs:
  package-web:
    name: Package Web
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: ubuntu-latest
      task: ylcs-app:web-app:webPublish
      submodules: recursive