name: ReleaseWindows
on:
  push:
    tags:
      - 'windows*'
jobs:
  package-windows:
    name: Package Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: 25
          cache: gradle
          cache-dependency-path: |
            ./*.gradle*
            ./**/gradle-wrapper.properties

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
          export-path-to-vs: VS_PATH

      - name: Build
        run: ./gradlew ylcs-app:desktop-app:desktopPublish