name: ReleaseAndroid
on:
  push:
    tags:
      - 'android*'
jobs:
  package-android:
    name: Package Android
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: ubuntu-latest
      task: ylcs-app:android-app:androidPublish
      submodules: recursive
      android: true
