name: ReleaseLinux
on:
  push:
    tags:
      - 'linux*'
jobs:
  package-linux:
    name: Package Linux
    # 用太新的 Ubuntu 会导致 native 库链接的 glibc 版本过高，导致无法在较旧的 Linux 上运行
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: 25
          cache: gradle
          cache-dependency-path: |
            ./*.gradle*
            ./**/gradle-wrapper.properties

      - name: Build
        run: ./gradlew ylcs-app:desktopApp:desktopPublish