name: ReleaseMacOS
on:
  push:
    tags:
      - 'macos*'
jobs:
  package-macos:
    name: Package macOS
    uses: $/.github/workflows/gradle-build.yml
    with:
      runner: macos-26
      task: ylcs-app:desktop-app:desktopPublish
      submodules: recursive